seafile:
  admin_email: admin@example.com
  admin_password: ChangeMe123!
  hostname: seafile.local
  protocol: http
  site_root: /
  timezone: Etc/UTC
mysql:
  root_password: RootPass123!
  user_password: DbPass123!
redis:
  password: ''
jwt:
  private_key: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
services:
  enable_seadoc: false
  enable_notification_server: false
  enable_seafile_ai: false
  enable_caddy: false
network:
  web_port:
    bind_mode: published
    port_number: 8082
ix_volumes:
  seafile-data: /opt/tests/mnt/seafile/data
  seafile-db: /opt/tests/mnt/seafile/db
  seafile-caddy: /opt/tests/mnt/seafile/caddy
  seafile-seadoc: /opt/tests/mnt/seafile/seadoc
storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: seafile-data
      acl_enable: false
      create_host_path: true
  db:
    type: ix_volume
    ix_volume_config:
      dataset_name: seafile-db
      acl_enable: false
      create_host_path: true
  caddy:
    type: ix_volume
    ix_volume_config:
      dataset_name: seafile-caddy
      acl_enable: false
      create_host_path: true
  seadoc:
    type: ix_volume
    ix_volume_config:
      dataset_name: seafile-seadoc
      acl_enable: false
      create_host_path: true
  redis:
    type: temporary
run_as:
  user: 568
  group: 568
